__author__ = 'Fabrice Servais'


class Configuration:
    """
    (type,  key, name) : {
        'state': ...
        'transaction': ...
        'connector': ...
        'value': ...
        'target': ...
        'device': ...
    }
    """

    def __init__(self, config_dict):

        for k, v in config_dict.iteritems():
            self.type, self.key, self.name = k

            self.state = v.get('state', -1)
            self.transaction = v.get('transaction', -1)
            self.connector = v.get('connector', None)
            self.value = v.get('value', None)
            if self.value is not None and type(self.value) is dict:
                self.value = Configuration(self.value)

            self.target = v.get('target', "")
            self.device = v.get('device', None)

            self.acked_state = v.get('acked_state', -1)
            self.ctx_name = v.get('ctxName', None)
            self.tenant = v.get('tenant', None)
            self.txid = v.get('txid', -1)
            self.abs_graph = v.get('absGraph', None)



if __name__ == "__main__":
    c = {(0, '', 5229): {'ackedState': 0,
                         'ctxName': 'Ciscoctx1',
                         'state': 1,
                         'tenant': 'Cisco',
                         'transaction': 0,
                         'txid': 10000,
                         'value': {(1, '', 5973): {'absGraph': 'WebGraph',
                                                   'ackedState': 0,
                                                   'state': 1,
                                                   'transaction': 0,
                                                   'value': {(3, 'VirtualServer', 'lb'): {'ackedState': 0,
                                                                                          'state': 1,
                                                                                          'transaction': 0,
                                                                                          'value': {(2, 'external',
                                                                                                     'external'): {
                                                                                              'ackedState': 0,
                                                                                              'state': 1,
                                                                                              'transaction': 0,
                                                                                              'value': {(9, '',
                                                                                                         'HAProxy_external_2818048_32770'): {
                                                                                                  'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'target': 'HAProxy_external_2818048_32770',
                                                                                                  'transaction': 0}}},
                                                                                              (2, 'internal',
                                                                                               'internal'): {
                                                                                                  'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': {(
                                                                                                      9, '',
                                                                                                      'HAProxy_internal_2818048_49156'): {
                                                                                                      'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'HAProxy_internal_2818048_49156',
                                                                                                      'transaction': 0}}},
                                                                                              (4, 'backendCfg',
                                                                                               'backendCfg'): {
                                                                                                  'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': {(6,
                                                                                                             'backendCfgRel',
                                                                                                             'backendCfgRel'): {
                                                                                                      'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'webserver',
                                                                                                      'transaction': 0}}},
                                                                                              (4, 'frontendCfg',
                                                                                               'frontendCfg'): {
                                                                                                  'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': {(6,
                                                                                                             'frontendCfgRel',
                                                                                                             'frontendCfgRel'): {
                                                                                                      'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'webVirtualServer',
                                                                                                      'transaction': 0}}}}}}},
                                   (4, 'backend', 'webserver'): {'ackedState': 0,
                                                                 'state': 1,
                                                                 'transaction': 0,
                                                                 'value': {(5, 'mode', 'mode'): {'ackedState': 0,
                                                                                                 'state': 1,
                                                                                                 'transaction': 0,
                                                                                                 'value': 'http'},
                                                                           (6, 'server', 'server1'): {'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'webserver1',
                                                                                                      'transaction': 0},
                                                                           (6, 'server', 'server2'): {'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'webserver2',
                                                                                                      'transaction': 0},
                                                                           (6, 'server', 'server3'): {'ackedState': 0,
                                                                                                      'state': 1,
                                                                                                      'target': 'webserver3',
                                                                                                      'transaction': 0}}},
                                   (4, 'frontend', 'webVirtualServer'): {'ackedState': 0,
                                                                         'state': 1,
                                                                         'transaction': 0,
                                                                         'value': {
                                                                             (4, 'bind', 'bind'): {'ackedState': 0,
                                                                                                   'state': 1,
                                                                                                   'transaction': 0,
                                                                                                   'value': {(5,
                                                                                                              'address',
                                                                                                              'address'): {
                                                                                                       'ackedState': 0,
                                                                                                       'state': 1,
                                                                                                       'transaction': 0,
                                                                                                       'value': '10.0.0.1'},
                                                                                                       (5, 'port',
                                                                                                        'port'): {
                                                                                                           'ackedState': 0,
                                                                                                           'state': 1,
                                                                                                           'transaction': 0,
                                                                                                           'value': '80'}}},
                                                                             (5, 'mode', 'mode'): {'ackedState': 0,
                                                                                                   'state': 1,
                                                                                                   'transaction': 0,
                                                                                                   'value': 'http'},
                                                                             (5, 'name', 'name'): {'ackedState': 0,
                                                                                                   'state': 1,
                                                                                                   'transaction': 0,
                                                                                                   'value': 'webVirtualServer'}}},
                                   (4, 'server', 'webserver1'): {'ackedState': 0,
                                                                 'state': 1,
                                                                 'transaction': 0,
                                                                 'value': {(5, 'address', 'address1'): {'ackedState': 0,
                                                                                                        'state': 1,
                                                                                                        'transaction': 0,
                                                                                                        'value': '192.168.10.2'},
                                                                           (5, 'name', 'name1'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': 'webserver1'},
                                                                           (5, 'port', 'port1'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': '80'}}},
                                   (4, 'server', 'webserver2'): {'ackedState': 0,
                                                                 'state': 1,
                                                                 'transaction': 0,
                                                                 'value': {(5, 'address', 'address1'): {'ackedState': 0,
                                                                                                        'state': 1,
                                                                                                        'transaction': 0,
                                                                                                        'value': '192.168.10.3'},
                                                                           (5, 'name', 'name1'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': 'webserver2'},
                                                                           (5, 'port', 'port2'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': '80'}}},
                                   (4, 'server', 'webserver3'): {'ackedState': 0,
                                                                 'state': 1,
                                                                 'transaction': 0,
                                                                 'value': {(5, 'address', 'address1'): {'ackedState': 0,
                                                                                                        'state': 1,
                                                                                                        'transaction': 0,
                                                                                                        'value': '192.168.10.4'},
                                                                           (5, 'name', 'name1'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': 'webserver3'},
                                                                           (5, 'port', 'port3'): {'ackedState': 0,
                                                                                                  'state': 1,
                                                                                                  'transaction': 0,
                                                                                                  'value': '80'}}},
                                   (7, '', '2818048_32770'): {'ackedState': 0,
                                                              'state': 1,
                                                              'tag': 437,
                                                              'transaction': 0,
                                                              'type': 1},
                                   (7, '', '2818048_49156'): {'ackedState': 0,
                                                              'state': 1,
                                                              'tag': 371,
                                                              'transaction': 0,
                                                              'type': 1},
                                   (8, '', 'HAProxy_external_2818048_32770'): {'ackedState': 0,
                                                                               'encap': '2818048_32770',
                                                                               'state': 1,
                                                                               'transaction': 0,
                                                                               'value': {},
                                                                               'vif': 'HAProxy_external'},
                                   (8, '', 'HAProxy_internal_2818048_49156'): {'ackedState': 0,
                                                                               'encap': '2818048_49156',
                                                                               'state': 1,
                                                                               'transaction': 0,
                                                                               'value': {},
                                                                               'vif': 'HAProxy_internal'},
                                   (10, '', 'HAProxy_external'): {'OspfVEncapAscCfg': {},
                                                                  'ackedState': 0,
                                                                  'cifs': {'dev1': 'eth0'},
                                                                  'state': 1,
                                                                  'transaction': 0},
                                   (10, '', 'HAProxy_internal'): {'OspfVEncapAscCfg': {},
                                                                  'ackedState': 0,
                                                                  'cifs': {'dev1': 'eth1'},
                                                                  'state': 1,
                                                                  'transaction': 0}}}}

    nginxServiceAuditConfig = { (0, '', 5787): { 'ackedstate': 0,
                   'ctxName': 'VRF_NG',
                   'state': 1,
                   'tenant': 'NGINX',
                   'transaction': 0,
                   'txid': 10000,
                   'value': { (1, '', 12097): { 'absGraph': 'NginxServiceGraph',
                                                'ackedstate': 0,
                                                'state': 1,
                                                'transaction': 0,
                                                'value': { (3, 'Load_balancer', 'ADC'): { 'ackedstate': 0,
                                                                                          'state': 1,
                                                                                          'transaction': 0,
                                                                                          'value': { (2, 'external', 'external'): { 'ackedstate': 0,
                                                                                                                                    'state': 1,
                                                                                                                                    'transaction': 0,
                                                                                                                                    'value': { (9, '', 'NginxDevice_external_2162688_49158'): { 'ackedstate': 0,
                                                                                                                                                                                                'state': 1,
                                                                                                                                                                                                'target': 'NginxDevice_external_2162688_49158',
                                                                                                                                                                                                'transaction': 0}}},
                                                                                                     (2, 'internal', 'internal'): { 'ackedstate': 0,
                                                                                                                                    'state': 1,
                                                                                                                                    'transaction': 0,
                                                                                                                                    'value': { (9, '', 'NginxDevice_internal_2162688_49158'): { 'ackedstate': 0,
                                                                                                                                                                                                'state': 1,
                                                                                                                                                                                                'target': 'NginxDevice_internal_2162688_49158',
                                                                                                                                                                                                'transaction': 0}}},
                                                                                                     (4, 'frontendServerCfg', 'frontendServerCfg'): { 'ackedstate': 0,
                                                                                                                                                      'state': 1,
                                                                                                                                                      'transaction': 0,
                                                                                                                                                      'value': { (6, 'frontendServerRel', 'frontendServerRel'): { 'ackedstate': 0,
                                                                                                                                                                                                                  'state': 1,
                                                                                                                                                                                                                  'target': 'frontendServer',
                                                                                                                                                                                                                  'transaction': 0}}},
                                                                                                     (4, 'upstreamCfg', 'upstreamCfg'): { 'ackedstate': 0,
                                                                                                                                          'state': 1,
                                                                                                                                          'transaction': 0,
                                                                                                                                          'value': { (6, 'upstreamRel', 'upstreamRel'): { 'ackedstate': 0,
                                                                                                                                                                                          'state': 1,
                                                                                                                                                                                          'target': 'upstream',
                                                                                                                                                                                          'transaction': 0}}}}}}},
                              (4, 'frontendServer', 'frontendServer'): { 'ackedstate': 0,
                                                                         'state': 1,
                                                                         'transaction': 0,
                                                                         'value': { (6, 'listen', 'listen'): { 'ackedstate': 0,
                                                                                                               'state': 1,
                                                                                                               'target': 'listen',
                                                                                                               'transaction': 0},
                                                                                    (6, 'location', 'location'): { 'ackedstate': 0,
                                                                                                                   'state': 1,
                                                                                                                   'target': 'location',
                                                                                                                   'transaction': 0}}},
                              (4, 'listen', 'listen'): { 'ackedstate': 0,
                                                         'state': 1,
                                                         'transaction': 0,
                                                         'value': { (5, 'port', 'port'): { 'ackedstate': 0,
                                                                                           'state': 1,
                                                                                           'transaction': 0,
                                                                                           'value': '80'}}},
                              (4, 'location', 'location'): { 'ackedstate': 0,
                                                             'state': 1,
                                                             'transaction': 0,
                                                             'value': { (5, 'proxy_pass', 'proxy_pass'): { 'ackedstate': 0,
                                                                                                           'state': 1,
                                                                                                           'transaction': 0,
                                                                                                           'value': 'proxy_pass'},
                                                                        (5, 'uri', 'uri'): { 'ackedstate': 0,
                                                                                             'state': 1,
                                                                                             'transaction': 0,
                                                                                             'value': '/'}}},
                              (4, 'upstream', 'upstream'): { 'ackedstate': 0,
                                                             'state': 1,
                                                             'transaction': 0,
                                                             'value': { (4, 'server', 'server'): { 'ackedstate': 0,
                                                                                                   'state': 1,
                                                                                                   'transaction': 0,
                                                                                                   'value': { (5, 'ip', 'ip'): { 'ackedstate': 0,
                                                                                                                                 'state': 1,
                                                                                                                                 'transaction': 0,
                                                                                                                                 'value': '10.9.218.1'},
                                                                                                              (5, 'port', 'port'): { 'ackedstate': 0,
                                                                                                                                     'state': 1,
                                                                                                                                     'transaction': 0,
                                                                                                                                     'value': '80'}}},
                                                                        (4, 'server', 'server2'): { 'ackedstate': 0,
                                                                                                    'state': 1,
                                                                                                    'transaction': 0,
                                                                                                    'value': { (5, 'ip', 'ip'): { 'ackedstate': 0,
                                                                                                                                  'state': 1,
                                                                                                                                  'transaction': 0,
                                                                                                                                  'value': '10.9.218.2'},
                                                                                                               (5, 'port', 'port'): { 'ackedstate': 0,
                                                                                                                                      'state': 1,
                                                                                                                                      'transaction': 0,
                                                                                                                                      'value': '80'}}},
                                                                        (5, 'upstreamName', 'upstreamName'): { 'ackedstate': 0,
                                                                                                               'state': 1,
                                                                                                               'transaction': 0,
                                                                                                               'value': 'backend'}}},
                              (7, '', '2162688_49158'): { 'ackedstate': 0,
                                                          'state': 1,
                                                          'tag': 2041,
                                                          'transaction': 0,
                                                          'type': 1},
                              (8, '', 'NginxDevice_external_2162688_49158'): { 'ackedstate': 0,
                                                                               'encap': '2162688_49158',
                                                                               'state': 1,
                                                                               'transaction': 0,
                                                                               'vif': 'NginxDevice_external'},
                              (8, '', 'NginxDevice_internal_2162688_49158'): { 'ackedstate': 0,
                                                                               'encap': '2162688_49158',
                                                                               'state': 1,
                                                                               'transaction': 0,
                                                                               'vif': 'NginxDevice_internal'},
                              (10, '', 'NginxDevice_external'): { 'ackedstate': 0,
                                                                  'cifs': { 'NginxDevice_Device_1': 'eth2'},
                                                                  'state': 1,
                                                                  'transaction': 0},
                              (10, '', 'NginxDevice_internal'): { 'ackedstate': 0,
                                                                  'cifs': { 'NginxDevice_Device_1': 'eth0'},
                                                                  'state': 1,
                                                                  'transaction': 0}}}}

    config = Configuration(c)

    print(config.state)
